# Generated by Django 5.1.6 on 2025-03-05 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configApp', '0007_grouphomework_homework_topics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descriptions', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='homework',
            old_name='groupHome',
            new_name='groupHomeWork',
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configApp.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configApp.student')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configApp.attendancelevel')),
            ],
        ),
    ]
